service:
  AppMode: debug
  HttpPort: 3000

mysql:
  database: mysql
  host: 127.0.0.1
  port: 3306
  user: root
  password: qwe123
  dbname: todo_List

rabbitmq:
  rabbitMQ: amqp
  MQuser: guest
  MQpassword: guest
  MQhost: 127.0.0.1
  MQport: 5672